version: "3"
services:
  react-app:
    build:
        context: ./frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    build:
        context: ./backend
    ports:
      - "4000:4000"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
